### ISSUE TITLE
DeleteContentPart

### ISSUE THREAD

**Issue by davidkrivohlavy** [Permafrost/TundraTN#45]
Hi Lachlan,
Is there any chance of you creating a service to delete ContentPart from a given $bizdoc in TundraTN.  This would be the opposite of AddContentPart.  During testing, using Save/RestorePipeline, when I AddContentPart (using tundra.tn.document.content:add) to a $bizdoc I can only use the saved pipeline once.  This would be a handy feature to be able to delete content part from a bizdoc for testing purposes

Cheers,
David

**Comment by lachlan** [comment]
Another way to avoid getting errors in testing because a content part already exists is to set a unique part name, by included the current datetime for example.
